### PR TITLE
add oxidised methane to total CO2, rather than the atmospheric boxes

### PR DESCRIPTION
**Pull request by chrisroadmap**
# Pull request

addresses #93 

- [x] Tests added
- ~~Documentation added (where applicable)~~ N/A as fix
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

### CODE REVIEW

**Comment by rgieseke** [comment]
> Interestingly this doesn't fail any of the pre-calculated tests: so while it was implemented clunkily it wasn't affecting the model results.

Could this be because `fossilCH4_frac=0.` leading to `(molwt.C/molwt.CH4 * 0.001 * oxCH4_frac * fossilCH4_frac[t]))` being zero with this default?

**Comment by FrankErrickson** [comment]
> > Interestingly this doesn't fail any of the pre-calculated tests: so while it was implemented clunkily it wasn't affecting the model results.
> 
> Could this be because `fossilCH4_frac=0.` leading to `(molwt.C/molwt.CH4 * 0.001 * oxCH4_frac * fossilCH4_frac[t]))` being zero with this default?

This is actually how we first came across the oxidised CO2 issue. Tests comparing the Julia and Python results wouldn't pass when `fossilCH4_frac` was anything but the default 0.

**Review by znicholls — COMMENTED** [review]
Reading the comments, is it worth adding a test with the oxidisation fraction being non-zero?

**Comment by chrisroadmap** [comment]
Yep, leave it with me. I think the default is zero because we need some more scenario information on the CH4 fossil to total split which not all scenarios give. I remember the effect being quite small, will do some diagnostics.

**Comment by chrisroadmap** [comment]
So to summarise, this was an error, and yes 4x the intended amount of methane was being added to the atmospheric CO2. The impacts were small, which is probably why it went un-noticed, and you had to explicitly set a non-zero methane fraction in order to get this issue occurring.

**Comment by FrankErrickson** [comment]
@chrisroadmap Just wanted to double check, do the units also need to be adjusted now that the oxidised CH4 is being added to CO2 emissions rather than the carbon pools? The terms `molwt.C/molwt.CH4 * 0.001` appear in the current oxidised CH4 equation code, but not in Equation 6 of the FAIR v1.3 model paper (where it's described as additional CO2 emissions).

**Comment by FrankErrickson** [comment]
Also in the `carbon_cycle` function, are oxidised CH4 emissions now being added to the period `t-1`, but not the period `t` emissions?

**Comment by chrisroadmap** [comment]
> @chrisroadmap Just wanted to double check, do the units also need to be adjusted now that the oxidised CH4 is being added to CO2 emissions rather than the carbon pools?

Yes, I think so.

> Also in the carbon_cycle function, are oxidised CH4 emissions now being added to the period t-1, but not the period t emissions?

The loop runs from 1, so it picks up emissions starting from year 0.

**Comment by chrisroadmap** [comment]
As you can see it's a bit of a second order effect and causing a few headaches - we'll either reform or remove it in fair 2.0

**Comment by chrisroadmap** [comment]
hmm, this doesn't seem to play nice with the recently added restart branch. One for the future.

**Comment by znicholls** [comment]
> hmm, this doesn't seem to play nice with the recently added restart branch. One for the future.

too late now but I probably would have done this before the restarts...

**Comment by chrisroadmap** [comment]
Will close the PR now because methane oxidation is one of those hangover issues - but it will be addressed in a future v2.x

**Pull request closed without merging**
