### PR TITLE
Distribution

### PR DESCRIPTION
**Pull request by richardcode**
@znicholls I think we should merge your distribution version of the object oriented to the master now as this is essentially distributable. Would you agree?

### CODE REVIEW

**Comment by znicholls** [comment]
It depends on our timeline. Do we know a publication date? If we need it up soon then yes I would merge. If no I would like us to clean up a few leftover questions before we merge back into the master.
Also when we make this public, are we going to have the whole repository be public or just say the master branch?

**Comment by richardcode** [comment]
Don't know any publication date as of yet. Happy to keep the branch distinct for a while if you'd rather that while we continue to develop it. I reckon just the master public would make sense at the start at least... 
Will add this to the main PyPI repository today if you are ok with that as I think we need it to be available there to create the conda recipe from?

**Comment by znicholls** [comment]
Ok. 
Well my preference then would be to avoid showing the public all our little, silly, messy commits. Hence I would move over the current 'master' branch to the 'develop' branch and just have one commit, 'v0.0.0' or whatever in the master branch when we're happy with it. That way public users don't see all our mucking around fixing typos etc. and we can just push onto the master branch as we release each version. Or we just start a new repository called FAIR-public or something. 

You can also create conda recipes from scratch, see https://conda.io/docs/build_tutorials/pkgs2.html. However I think following https://conda.io/docs/build_tutorials/pkgs.html#conda-build-skeleton is easiest and then you just change the location of files from pypi to testpypi in the commands you run. 

Again the reason I'm hesitant to put it onto PyPI now is because it's so untested and messy (e.g. comments all over the place and some naming decisions which remain unresolved so might change the name of key files in future although maybe this is solved by the whole packaging thing...).

Ultimately I don't think any of this is major so if you want to just make a decision I'll live.

**Comment by znicholls** [comment]
Ok so I've just spent a bit of time mucking around trying to get the conda build stuff working without having the package on PyPI and have decided that it's not the smart way of doing things (as you probably already knew). 

So my suggestion would be to clean up this branch a bit more with things like adding tests, deciding on a naming convention and getting rid of any other leftover comments. Then merge into master. Then put it on PyPI. Then build the conda stuff from PyPI.

**Comment by znicholls** [comment]
Draft to do list before we merge into master:

- [ ] decide on naming of package, modules, classes
- [ ] decide versioning system
- [ ] implement tests
- [ ] add any more details we think are useful to setup.py ("classifiers" being the most obvious starting point)
- [ ] Update README

**Comment by znicholls** [comment]
Should we ever decide to do this again, here is my 'How to of distribution'. 


Filename: conda-pyPi-packaging-python-scripts-1_0.md  
Creation date: 2017-04-11 14:37:16  
Author: zebedeen  
Email: zebedee.nicholls@climate-energy-college.org  
Last modified by: zebedee  
Last modified time: 2017-04-19 12:30:43  

# Packaging python scripts 

*How to package python scripts into Conda and PyPi distributable packages*

----

# Table of Contents

1. [Packages and modules](#packages-and-modules)
    1. [The basics](#the-basics)
        1. [Setup](#setup)
        1. [Explanation](#explanation)
    1. [Executing modules as scripts](#executing-modules-as-scripts)
1. [Importing](#importing)
    1. [Basics](#basics)
    1. [dir()](#dir)
    1. [Options](#options)
        1. [Make the function available directly (same as above)](#make-the-function-available-directly-same-as-above)
        1. [Make the module available without its package prefix](#make-the-module-available-without-its-package-prefix)
        1. [Import an individual module from the package](#import-an-individual-module-from-the-package)
    1. [Sources and further reference](#sources-and-further-reference)
1. [\_\_init\_\_.py](#9595init9595py)
    1. [setup](#setup_1)
    1. [Motivation](#motivation)
    1. [Solving with `__init__`.py](#solving-with-`__init__`py)
    1. [Sources and further reference](#sources-and-further-reference_1)
1. [Distributing](#distributing)
    1. [An option](#an-option)
    1. [setuptools](#setuptools)
        1. [Installing setuptools](#installing-setuptools)
        1. [`setup.py`](#`setuppy`)
            1. [Basics](#basics_1)
            1. [README](#readme)
            1. [Other fields](#other-fields)
                1. [Specifying dependencies](#specifying-dependencies)
                1. [Long description](#long-description)
                1. [Keywords](#keywords)
                1. [url](#url)
                1. [Tests](#tests)
                1. [Other classifiers](#other-classifiers)
        1. [Source distributions and wheels](#source-distributions-and-wheels)
            1. [Create source distribution](#create-source-distribution)
            1. [Create wheel](#create-wheel)
            1. [`.gitignore`](#`gitignore`)
            1. [Installing with source distribution or wheel](#installing-with-source-distribution-or-wheel)
        1. [Sources and further reference](#sources-and-further-reference_2)
    1. [PiPY and pip](#pipy-and-pip)
        1. [Registering with PyPI](#registering-with-pypi)
        1. [Registering your package](#registering-your-package)
        1. [Upload to PyPI](#upload-to-pypi)
        1. [Test the install](#test-the-install)
        1. [Sources and further reference](#sources-and-further-reference_3)
    1. [Conda](#conda)



## Packages and modules

### The basics

#### Setup

Create a new directory, call it `melbournescmr`. Now create a subdirectory, call it `melbournep`. Now create two empty python files, one called `melbournem.py`, one called `__init__.py`. Your directory structure should look like this

```
melbournescmr/
    melbournep/
        __init__.py
        melbournem.py
```

#### Explanation

Your top level directory, in this case `melbournescmr`, is the root directory of your source code. If you use version control, this should also be the root of your source code management repository. For example, if you use git, this would be the root directory of your git repository. 

The name of this directory can be whatever you want but generally will be your package name. In this guide we'll call this directory `melbournescmr` to remind us that it's the root of our source code management repository. 

Your package is contained in a subdirectory. This directory contains all your python modules (i.e. scripts) which define the classes, functions, variables etc. etc. used in the package. You can also have subpackages, subsubpackages etc.. In this guide our package is called `melbournep`. The 'p' suffix reminds us that this directory is our package.

The `__init__.py` file tells Python that our `melbournep` directory is a Python package. Its contents are run whenever we `import` our package or one of its submodules/classes so for now let's make its contents:

```python
print "ran melbournep/__init__.py"
```

Your module is a .py file which contains code which defines classes, functions, variables etc. etc. There can be multiple modules in a package and you can have modules in subpackages, subsubpackages etc. The only module we have defined so far is the `melbournem` module. The 'm' suffix reminds us that this is a module. 

Whenever a module is imported, all of the code in it is executed. This is a very important point to keep in mind as it can be very useful. For example, any `import` statements required for your module can be left in the module and don't need to be included in, for example, `__init__.py`. 

For now save `melbournem` with the following contents:

```python
print "Importing melbournem"
print "The whole module is run when we import it."
print "Including any import statements we might have at the top of our module."

def melbournef():
    return("Here's the text that is returned. Melbourne has been voted the "
           "world's most livable city multiple times.")
```

The 'f' suffix reminds us that `melbournef` is a function.

*Note:* All module and package names should be all lowercase and be underscore-separated or have no word-separators at all. If you're going to release your package on PyPI or Conda then the name should be unique too. 

### Executing modules as scripts

When Python modules are run with `python [module].py [arguments]` then their `__name__` is set to `__main__`. Many programs take advantage of this by having the code do something slightly different when it's executed as a script. For example the following code defines a module which provides an add function but also returns the added numbers **only** if it is called with `python add.py [argument 1] [argument 2]`

```python
# add.py
def add(x,y):
    return x + y

if __name == "__main__":
    import sys
    return float(sys.argv[1]) + float(sys.argv[2])

### Sources and further reference

#### The basics

https://www.blog.pythonlibrary.org/2012/07/08/python-201-creating-modules-and-packages/

https://python-packaging.readthedocs.io/en/latest/minimal.html

https://docs.python.org/2/tutorial/modules.html

https://pythonconquerstheuniverse.wordpress.com/2009/10/15/python-packages/

http://pythoncentral.io/how-to-create-a-python-package/

#### Executing modules as scripts

https://www.blog.pythonlibrary.org/2012/07/08/python-201-creating-modules-and-packages/

https://docs.python.org/2/tutorial/modules.html

http://effbot.org/pyfaq/tutor-what-is-if-name-main-for.htm

```

## Importing

### Basics

Packages and modules can be imported in many different ways with different effects. The most useful is importing the desired function directly. 

```python
# import melbournef directly
# the output shows that the __init__.py and melbournem.py files are run
>>> from melbournep.melbournem import melbournef
ran melbournep/__init__.py
Importing melbournem
The whole module is run when we import it.
Including any import statements we might have at the top of our module.

# call it
>>> melbournef()
"Here's the text that is returned. Melbourne has been voted the world's most livable city multiple times."
```

However this **only** works if your working directory contains the `melbournep` directory. If it doesn't then Python can't find the `melbournep` package.

```python
# our current working directory contains the melbournep package
>>> import os
>>> os.listdir('.')
['melbournep']

# so we can import the package
>>> from melbournep.melbournem import melbournef
ran melbournep/__init__.py
Importing melbournem
The whole module is run when we import it.
Including any import statements we might have at the top of our module.
>>> melbournef()
"Here's the text that is returned. Melbourne has been voted the world's most livable city multiple times."
```

```python
# our current working directory doesn't contain the melbournep package
>>> import os
>>> os.listdir('.')
['test.py', 'Animals', 'funniest', 'melbournescmr']

# so we can't import the package
>>> from melbournep import melbournem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named melbournep
```

### dir()

The built-in `dir()`  function lists the names that we have currently defined whether they be variables, modules, functions, classes, packages etc. It lets you keep track of what you've imported and defined. 

With arguments, `dir([module name])` lists the names that a module has defined. It lets you keep track of the names that can be called from a module with dot notation e.g. `[module].[submodule].[function]`

### Options

Using `dir()`, we can see the effect of importing modules and packages in different ways.

#### Make the function available directly (same as above)

```python
# nothing imported yet
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__']

# import our function
>>> from melbournep.melbournem import melbournef
ran melbournep/__init__.py
Importing melbournem
The whole module is run when we import it.
Including any import statements we might have at the top of our module.

# check it was imported
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__', 'melbournef']

# the function can be called directly
>>> melbournef()
"Here's the text that is returned. Melbourne has been voted the world's most livable city multiple times."
```

#### Make the module available without its package prefix

```python
# nothing imported yet
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__']

# import our module
>>> from melbournep import melbournem
ran melbournep/__init__.py
Importing melbournem
The whole module is run when we import it.
Including any import statements we might have at the top of our module.

# check it was imported
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__', 'melbournem']

# check which functions and classes our module defines
>>> dir(melbournem)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', 'melbournef']

# to call the function we must use dot notation
>>> melbournem.melbournef()
"Here's the text that is returned. Melbourne has been voted the world's most livable city multiple times."

# the function is not available directly
>>> melbournef()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'melbournef' is not defined
```

#### Import an individual module from the package

```python
# nothing imported yet
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__']

# import our module
>>> import melbournep.melbournem
ran melbournep/__init__.py
Importing melbournem
The whole module is run when we import it.
Including any import statements we might have at the top of our module.

# check it was imported, note that 'melbournep.melbournem' is not explicitly 
# defined, only 'melbournep'
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__', 'melbournep']
>>> dir(melbournep)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'melbournem']

# to call the function we must use its full name
>>> melbournep.melbournem.melbournef()
"Here's the text that is returned. Melbourne has been voted the world's most livable city multiple times."

# the module is not available directly
>>> melbournem.melbournef()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'melbournem' is not defined
```

*Note:* when using `from package import item`, the item can be either a submodule (or subpackage) of the package, or some other name defined in the package, like a function, class or variable. The import statement first tests whether the item is defined in the package; if not, it assumes it is a module and attempts to load it. If it fails to find it, an ImportError exception is raised.

Contrarily, when using syntax like `import item.subitem.subsubitem`, each item except for the last must be a package; the last item can be a module or a package but can’t be a class or function or variable defined in the previous item.

### Sources and further reference

https://www.blog.pythonlibrary.org/2012/07/08/python-201-creating-modules-and-packages/

https://python-packaging.readthedocs.io/en/latest/minimal.html

https://docs.python.org/2/tutorial/modules.html

https://pythonconquerstheuniverse.wordpress.com/2009/10/15/python-packages/

http://pythoncentral.io/how-to-create-a-python-package/

## \_\_init\_\_.py

### setup

Let's add another function, z2f, to our `melbournem` module by changing it's contents to:

```python
print "Importing melbournem"
print "The whole module is run when we import it."
print "Including any import statements we might have at the top of our module."

def melbournef():
    return("Here's the text that is returned. Melbourne has been voted the "
           "world's most livable city multiple times.")

def z2f():
    return("A different text. Melbourne has 4.5 million inhabitants")
```

Let's also add another module, `z2m`, with contents:

```python
def addf(x,y):
    return (x+y)

def csdf():
    return("Where in the world is Carmen San Diego?")
```

So now our directory structure should look like (you might have some `.pyc` files too, ignore these):

```
melbournescmr/
    melbournep/
        __init__.py
        melbournem.py
        z2m.py
```

### Motivation

If we want to have all the functions in our pacakage available to us we have to do something like

```python
# nothing imported
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__']

# import melbournem module
>>> from melbournep import melbournem
ran melbournep/__init__.py
Importing melbournem
The whole module is run when we import it.
Including any import statements we might have at the top of our module.

# check it's there
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__', 'melbournem']

# see which submodules, classes and functions it defines
>>> dir(melbournem)
['__builtins__', '__doc__', '__file__', '__name__', '__package__',  
 'melbournef', 'z2f']

# import z2m module
>>> from melbournep import z2m

# check it's there
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__', 'melbournem', 'z2m']

# see which submodules, classes and functions it defines
>>> dir(z2m)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', 
 'addf', 'csdf']

# call some functions 
>>> z2m.csdf()
'Where in the world is Carmen San Diego?'
>>> melbournem.z2f()
'A different text. Melbourne has 4.5 million inhabitants'
```

### Solving with `__init__`.py

Importing each module/function/class from a package individually can be a pain so it is common practice to use the fact that `__init__.py` is run when we import `melbournep` or one of its submodules/subpackages to skip this step. For example, change the contents of `melbournep/__init__.py` to:

```python
print "ran melbournep/__init__.py"

from melbournem import melbournef
from melbournem import z2f

from z2m import addf
from z2m import csdf
```

Now when we import `melbournep` or one of its submodules/subpackages, all the other ones are available to us too through dot notation. 

*Note:* `__init__.py` and the code in our module are only run the first time we import in a session!

```python
# nothing yet imported
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__']

# import melbournep
>>> import melbournep
ran melbournep/__init__.py
Importing melbournem
The whole module is run when we import it.
Including any import statements we might have at the top of our module.

# __init__.py has run and melbournep has been imported
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__', 'melbournep']

# our __init__.py script makes all our other functions available through dot 
# notation
>>> dir(melbournep)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 
 'addf', 'csdf', 'melbournef', 'melbournem', 'z2f', 'z2m']

# try calling some functions
>>> melbournep.z2f()
'A different text. Melbourne has 4.5 million inhabitants'
>>> melbournep.addf(3,6)
9

# importing melbournep again doesn't run __init__.py again!
>>> import melbournep
>>>
# importing melbournem again doesn't run the code in melbournem.py again!
>>> from melbournep import melbournem
>>> 
```

If you want to see a far more complex example of how to use `__init__.py` then have a look at [`__init__.py` on pymagicc github](https://github.com/openclimatedata/pymagicc/blob/master/pymagicc/__ init__.py).

### Sources and further reference

https://www.blog.pythonlibrary.org/2012/07/08/python-201-creating-modules-and-packages/

https://python-packaging.readthedocs.io/en/latest/minimal.html

https://docs.python.org/2/tutorial/modules.html

http://pythoncentral.io/how-to-create-a-python-package/

## Distributing

### An option

As we now know how to make a Python package with modules and functions that are callable from Python, we could just stop here. Unfortunately this would require us to have all the packages, modules and functions we need in our working directory. Cleary this would quickly become a pain. 

To avoid this, various tools have been developed to help make python (and other language) packages distributable and easily installable. 

### setuptools

setuptools is a Python package which is used to easily download, build, install, upgrade, and uninstall Python packages. It seems to be the most widely used and best package for this purpose so it's what I use. 

#### Installing setuptools

If you haven't yet, make sure you have installed pip. Instructions: [https://pip.pypa.io/en/stable/installing/](https://pip.pypa.io/en/stable/installing/)

To install setuptools run the following in terminal

```
pip install -U pip setuptools
``` 

#### `setup.py`

This file acts as the main entrypoint to register the package name on PyPI and upload source distributions. It contains a single call to setuptools so it can also be used to install the package locally.

##### Basics

In the root of your source code management repository create a file called `setup.py` with the following contents.

```python
from setuptools import setup

setup(name='melbournen',
      version='0.1.0',
      description='Melbourne examples',
      author='City of Melbourne',
      author_email='mel@example.com',
      packages=['melbournep'],
      zip_safe=False)
```

I have used `melbournen` for the name to highlight that this is just the name that is used by setuptools and doesn't actually affect the package or module name. Your directory should now have the following structure.

```
melbournescmr/
    melbournep/
        __init__.py
        melbournem.py
        z2m.py
    setup.py
```

We can now install the package locally into the active environment/for our default version of Python by running the following command whilst in the directory containing `setup.py`

```
pip install [path to directory containing setup.py]
```

Hence in our case we run

```
pip install melbournescmr/
```

The output should look something like 

```
Processing ./melbournescmr
Installing collected packages: melbournen
  Running setup.py install for melbournen ... done
Successfully installed melbournen-0.1.0
```

We can check that our package was installed using `pip list`. The output should be something like

```
Package        Version Location
-------------- ------- ----------------------------
...   
melbournen     0.1.0
...
```

We can now import our modules, packages and functions in Python, irrespective of our current working directory.

```python
# We're in a directory that doesn't contain our package
>>> import os
>>> os.listdir('.')
['something.txt']

# We can import the package defined in setup.py and then call functions
>>> import melbournep
ran melbournep/__init__.py
Importing melbournem
The whole module is run when we import it.
Including any import statements we might have at the top of our module.

>>> dir()
['__builtins__', '__doc__', '__name__', '__package__', 'melbournep', 'os']
>>> dir(melbournep)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 
 'addf', 'csdf', 'melbournef', 'melbournem', 'z2f', 'z2m']
>>> melbournep.melbournef()
"Here's the text that is returned. Melbourne has been voted the world's most livable city multiple times."

# However the name, melbournen, doesn't define a package so can't be imported
>>> import melbournen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named melbournen
```

The fact that the `name` field in `setup.py` doesn't actually let you import the package is why most people tend to make `name` and `packages` the same. If you want to break a big package down into more manageable bits then you can use subpackages which can be called with dot notation i.e. `from [package].[subpackage] import function`

Finally we can uninstall the package using 

```
pip uninstall melbournen
```

Answer 'y' to the question to proceed with uninstall

```
pip uninstall melbournen
Uninstalling melbournen-0.1.0:
  .../miniconda2/lib/python2.7/site-packages/melbournen-0.1.0-py2.7.egg-info
  .../miniconda2/lib/python2.7/site-packages/melbournep/__init__.py
  .../miniconda2/lib/python2.7/site-packages/melbournep/__init__.pyc
  .../miniconda2/lib/python2.7/site-packages/melbournep/melbournem.py
  .../miniconda2/lib/python2.7/site-packages/melbournep/melbournem.pyc
  .../miniconda2/lib/python2.7/site-packages/melbournep/z2m.py
  .../miniconda2/lib/python2.7/site-packages/melbournep/z2m.pyc
Proceed (y/n)? y
  Successfully uninstalled melbournen-0.1.0
```

##### README

In the same directory as `setup.py`, add a `README` file as well as a file called `MANIFEST.in`. For this exercise we will use markdown for our `README` file so your scmr should now look like 

```
melbournescmr/
    melbournep/
        __init__.py
        melbournem.py
        z2m.py
    setup.py
    README.md
    MANIFEST.in
```

Obviously you can use whatever file format you want for your `README` file, common ones are `.txt`, `.rst` and `.md`.

To tell setuptools to include `README.md` when generating source distributions, `MANIFEST.in` should contain 

```
include README.[extension]
```

which in our case would be 

```
include README.md
```

You must also add the `include_package_data=True` argument to `setup.py`

```python
setup(
      ...
      include_package_data=True,
      ...
      )
```

##### Other fields

###### Specifying dependencies

In `setup.py` add an `install_requires` argument. The value of `install_requires` should be a list like so

```python
setup(
      ...
      install_requires=['numpy',
                        'scipy'],
      ...
      )
```

Each dependency must match the name of the file on PyPI. (You can also specify packages which aren’t on PyPI with some massaging but we shouldn't need this for a while.)

Now when we install `melbournen` we can see that `setuptools` also checks for the dependencies.

```
$ pip install melbournescmr/
Processing ./melbournescmr
Requirement already satisfied: numpy in .../miniconda2/lib/python2.7/site-packages (from melbournen==0.1.0)
Requirement already satisfied: scipy in .../miniconda2/lib/python2.7/site-packages (from melbournen==0.1.0)
Installing collected packages: melbournen
  Running setup.py install for melbournen ... done
Successfully installed melbournen-0.1.0
```

###### Long description

We should also include a longer description in our `setup.py` file. We can do this with the `long_description` keyword. 

```python
setup(
      ...
      long_description="We can put some longer description in here.",
      ...
      )
```

If you have a `README` then a little bit of code to read it in keeps things all in one place.

```python
def readme():
    with open('[name of README file with extension]') as f:
        return f.read()

setup(
      ...
      long_description=readme(),
      ...
      )
```

###### Keywords

In `setup.py` add a `keywords` argument. It should be a space separated list of keywords e.g.

```python
setup(
      ...
      keywords = "melbourne example boasting",
      ...
      )
```

###### url

In `setup.py` add a `url` argument. It should be a link to an online repository where your code is hosted.

```python
setup(
      ...
      url="http://melbourneisthebest.com/code",
      ...
      )
```

###### Tests

Place tests in a submodule of the directory containing your package i.e.

```
melbournescmr/
    melbournep/
            tests/
                __init__.py
                test_melbournef.py
        __init__.py
        melbournem.py
        z2m.py
    setup.py
    README.md
    MANIFEST.in
```

In `test_melbournef.py` we use a `unittest.TestCase` subclass which is overkill for now but provides good infrastructure for later development.

```
from unittest import TestCase

import melbournep

class TestMelbournef(TestCase):
    def test_is_string(self):
        s = melbournep.melbournef()
        self.assertTrue(isinstance(s, basestring))
```

To use the tests we should then install `nose`

```
pip install nose
```

The tests can then be run by calling `nosetests` in terminal from the scmr. 

```
$ pwd
.../melbournescmr
$ nosetests
.
----------------------------------------------------------------------
Ran 1 test in 0.074s

OK
```

To integrate these tests into `setup.py` add the following lines

```python
setup(
    ...
    test_suite='nose.collector',
    tests_require=['nose'],
    ...
)
```

so that our tests can simply be run by calling `python setup.py test` from our scmr, with output something like

```
$ pwd
.../melbournescmr
$ python setup.py test
running test
running egg_info
creating melbournen.egg-info
writing requirements to melbournen.egg-info/requires.txt
writing melbournen.egg-info/PKG-INFO
writing top-level names to melbournen.egg-info/top_level.txt
writing dependency_links to melbournen.egg-info/dependency_links.txt
writing manifest file 'melbournen.egg-info/SOURCES.txt'
reading manifest file 'melbournen.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'melbournen.egg-info/SOURCES.txt'
running build_ext
test_is_string (melbournep.tests.test_melbournef.TestMelbournef) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
```

###### Other classifiers

Better package metadata can be added with the `classifiers` keyword alongside some others. For a full list of arguments to `classifiers` visit http://pypi.python.org/pypi?%3Aaction=list_classifiers.

#### Source distributions and wheels

##### Create source distribution

To create the source distribution, from the scmr directory simply run

```
$ pwd
.../melbournescmr
$ python setup.py sdist
```

This creates `melbournescmr/dist/[package name]-[version].tar.gz` with terminal output something like: 

(Ignore the warnings. Using `.md` format for `README` is fine and we don't have a url for our package.)

```
running sdist
running egg_info
writing requirements to melbournen.egg-info/requires.txt
writing melbournen.egg-info/PKG-INFO
writing top-level names to melbournen.egg-info/top_level.txt
writing dependency_links to melbournen.egg-info/dependency_links.txt
reading manifest file 'melbournen.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'melbournen.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
warning: check: missing required meta-data: url

creating melbournen-0.1.0
creating melbournen-0.1.0/melbournen.egg-info
creating melbournen-0.1.0/melbournep
copying files to melbournen-0.1.0...
copying MANIFEST.in -> melbournen-0.1.0
copying README.md -> melbournen-0.1.0
copying setup.py -> melbournen-0.1.0
copying melbournen.egg-info/PKG-INFO -> melbournen-0.1.0/melbournen.egg-info
copying melbournen.egg-info/SOURCES.txt -> melbournen-0.1.0/melbournen.egg-info
copying melbournen.egg-info/dependency_links.txt -> melbournen-0.1.0/melbournen.egg-info
copying melbournen.egg-info/not-zip-safe -> melbournen-0.1.0/melbournen.egg-info
copying melbournen.egg-info/requires.txt -> melbournen-0.1.0/melbournen.egg-info
copying melbournen.egg-info/top_level.txt -> melbournen-0.1.0/melbournen.egg-info
copying melbournep/__init__.py -> melbournen-0.1.0/melbournep
copying melbournep/melbournem.py -> melbournen-0.1.0/melbournep
copying melbournep/z2m.py -> melbournen-0.1.0/melbournep
Writing melbournen-0.1.0/setup.cfg
creating dist
Creating tar archive
removing 'melbournen-0.1.0' (and everything under it)
```

##### Create wheel
To create a wheel (better version of previous compilations as far as I can tell, more [here](http://pythonwheels.com/), simply run

```
$ pwd
.../melbournescmr
$ python setup.py bdist_wheel
```

This creates `build/` and `dist/[package name]-[version]-[python version]-[some other identifier I don't know about yet].whl` inside our scmr directory. The output is something like

```
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/melbournep
copying melbournep/__init__.py -> build/lib/melbournep
copying melbournep/melbournem.py -> build/lib/melbournep
copying melbournep/z2m.py -> build/lib/melbournep
running egg_info
writing requirements to melbournen.egg-info/requires.txt
writing melbournen.egg-info/PKG-INFO
writing top-level names to melbournen.egg-info/top_level.txt
writing dependency_links to melbournen.egg-info/dependency_links.txt
reading manifest file 'melbournen.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'melbournen.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/melbournep
copying build/lib/melbournep/__init__.py -> build/bdist.linux-x86_64/wheel/melbournep
copying build/lib/melbournep/melbournem.py -> build/bdist.linux-x86_64/wheel/melbournep
copying build/lib/melbournep/z2m.py -> build/bdist.linux-x86_64/wheel/melbournep
running install_egg_info
Copying melbournen.egg-info to build/bdist.linux-x86_64/wheel/melbournen-0.1.0-py2.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/melbournen-0.1.0.dist-info/WHEEL
```

##### `.gitignore`

Once you've created your source distribution and wheel you should make sure that you have a well-configured `.gitignore` or similar file. This prevents compiled distributions from appearing in your source code repository, something you don't want. 

```
# Compiled python modules.
*.pyc

# Setuptools distribution folder.
/dist/

# Python egg metadata, regenerated from source files by setuptools.
/*.egg-info
/*.egg

# Build folder
/build
```

##### Installing with source distribution or wheel

Other users can then easily install the package by either of the `.tar.gz` or `.whl` files and running any of

```
pip install [project.whl file]
pip install [project.tar.gz file]
``` 
#### Sources and further reference

https://python-packaging.readthedocs.io/en/latest/minimal.html

https://packaging.python.org/distributing/

### PiPY and pip

Before you start, install `twine`, the package we'll use to communicate with the PyPI repository, by running the following in terminal

```
pip install twine
```

#### Registering with PyPI

If you haven't already done so, create a [PyPI](https://pypi.python.org/pypi) and a [TestPyPI](https://testpypi.python.org/pypi) account manually online. Don’t create an account through `python setup.py register` as there are security concerns.

To help you interact with the PyPI repositories, create a file in your home directory called `.pypirc` with contents

```
[distutils]
index-servers=
    pypi
    testpypi

[testpypi]
repository = https://testpypi.python.org/pypi
username = [username]

[pypi]
repository = https://pypi.python.org/pypi
username = [username]
```

#### Registering your package

To register the package with PyPI i.e. reserve the name, upload package metadata, and create the pypi.python.org webpage: 

`twine register dist/[pack-name-version].whl`

To register with the test site use:

`twine register dist/[pack-name-version].whl -r testpypi`

If you're not asked for your password then seomthing weird is going on.

#### Upload to PyPI

From the scmr directory simply run

`twine upload dist/* -r testpypi`

If you're not asked for your password then seomthing weird is going on.

#### Test the install

Once the package is uploaded, other users can install it with 

```
pip install [package name]
pip install -i https://testpypi.python.org/pypi [package name]
```

#### Sources and further reference

https://packaging.python.org/distributing/

https://python-packaging.readthedocs.io/en/latest/minimal.html

More detail on setup can can be found with `python setup.py --help-commands`

You can also do stuff with command line scripts, adding non-code files etc. which I haven't got to. 

### Conda

{Follow up} Also distributable with Conda. Note that Conda can be extended to handle more than just python, unlike pip. Easy way seems to be to follow https://conda.io/docs/build_tutorials/pkgs.html once you have a package on PyPI.

**Comment by richardcode** [comment]
@znicholls I've just updated the naming structure to simplify things a bit (d12ad03cfc880815e0eecda0ada8ffd4441eff1c). This improves the import syntax to... 
`from fair import *
f = FAIR()`
Happy to try to use the naming structure that you link to above from now on...

**Comment by znicholls** [comment]
@richardcode I don't think moving all the code into`__init__.py` is a good idea as it could make things incredibly messy in future should we ever want to scale up the package. It could also lead to unexpected conflicts and I've never seen anyone recommend it. 

Also I've seen many recommendations against using wildcard imports so I don't think we should be encouraging that either...

I do like changing the name from `fair_objo` to `fair`. Or even `fair_fm` to indicate that it's the forward model?

**Comment by richardcode** [comment]
@znicholls fair enough, probably good practise to keep them separate. Although I have seen it done to have a few functions in the __init__.py file (e.g. https://github.com/SciTools/iris/blob/master/lib/iris/__init__.py). 
I've added the statement `import forward` to __init__.py to allow the main function to be accessible as...
```python
import fair 
f = fair.forward.FAIR() 
```

**Comment by znicholls** [comment]
@richardcode I think there is a rogue `forward.py` sitting in the top level of the repository but otherwise looks good. I definitely agree that we could put the functions in `__init__.py`, I just don't think it's best practice. 

Looks good, if users want it to be more accessible they can also use 

```python
from fair.forward import FAIR
f = FAIR()
```

Looking at this now, do we want to rename the class from `FAIR` to `FAIRforward` or something (I can't remember the class naming capitalisation convention right now..)?

**Comment by richardcode** [comment]
@znicholls would be keen to road test this with some students this week by uploading a new "fair" version onto testpypi so it is accessible to them. Hope that sounds ok!

**Comment by znicholls** [comment]
Sounds perfect!

**Comment by richardcode** [comment]
@znicholls thanks for the spot! It's gone now...

**Pull request closed without merging**
