### PR TITLE
Make iirf_h a keyword parameter (formerly fixed at 100 years)

### LINKED ISSUE #4: Make integrated impulse response time horizon (100yrs) a keyword argument
Probably do some sensitivity tests afterwards. I wonder what happens if you fiddle around with it.

### PR DESCRIPTION
**Pull request by chrisroadmap**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

Fixes #4.

### CODE REVIEW

**Comment by chrisroadmap** [comment]
No rush on this one @znicholls

**Comment by znicholls** [comment]
Can you rebase onto master? It seems to be including changes from #57 too.

**Comment by chrisroadmap** [comment]
Yep, #57 was merged into master previously so the new branch includes these changes (`git rebase` confirms this branch is up to date with `master`). I've just made a small patch to the changelog and squashed it into the previous commit.

**Review by znicholls — APPROVED** [review]
Looks good @chrisroadmap. Thinking about the iirf_h parameter now, maybe there should be a warning in the docs that the results are fairly sensitive to this parameter and it can take some thinking to work out what is going in. Maybe that's just part of the fun.

**Comment by chrisroadmap** [comment]
Awesome. Will merge when back in office next week. I don't think the 100 year time horizon was ever meant to be modified but gives users another dial they can crank. For consistency `r0` and possibly also `rc` and `rt` would need to be modified as they are defined with respect to a 100 year time horizon.

**Pull request merged**
