### PR TITLE
Change imports to relative for Python3 compatibility

### PR DESCRIPTION
**Pull request by rgieseke**
Great work, nice to see a fully Python-based SCM.
I've made changes to the imports to be relative which I think should work for both 2.7 and Python3:

Python3
```
(venv) robert@pikbook ~/s/FAIR (py3-compatibility)> pytest tests/ --verbose
================ test session starts 
platform linux -- Python 3.6.1, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /home/robert/sources/FAIR/venv/bin/python3.6
cachedir: .cache
rootdir: /home/robert/sources/FAIR, inifile:
collected 9 items                                                                                                                                                                                                 

tests/test_fair.py::test_import PASSED                                                                                                                                                                      [ 11%]
tests/test_fair.py::test_no_arguments PASSED                                                                                                                                                                [ 22%]
tests/test_fair.py::test_zero_emissions PASSED                                                                                                                                                              [ 33%]
tests/test_fair.py::test_ten_GtC_pulse PASSED                                                                                                                                                               [ 44%]
tests/test_fair.py::test_multigas_fullemissions_error PASSED                                                                                                                                                [ 55%]
tests/test_fair.py::test_rcp3pd PASSED                                                                                                                                                                      [ 66%]
tests/test_fair.py::test_rcp45 PASSED                                                                                                                                                                       [ 77%]
tests/test_fair.py::test_rcp6 PASSED                                                                                                                                                                        [ 88%]
tests/test_fair.py::test_rcp85 PASSED                                                                                                                                                                       [100%]

============= 9 passed
```

Python 2

```
================ test session starts 
platform linux2 -- Python 2.7.13, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /home/robert/sources/FAIR/venv2/bin/python2
cachedir: .cache
rootdir: /home/robert/sources/FAIR, inifile:
collected 9 items                                                                                                                                                                                                 

tests/test_fair.py::test_import PASSED                                                                                                                                                                      [ 11%]
tests/test_fair.py::test_no_arguments PASSED                                                                                                                                                                [ 22%]
tests/test_fair.py::test_zero_emissions PASSED                                                                                                                                                              [ 33%]
tests/test_fair.py::test_ten_GtC_pulse PASSED                                                                                                                                                               [ 44%]
tests/test_fair.py::test_multigas_fullemissions_error PASSED                                                                                                                                                [ 55%]
tests/test_fair.py::test_rcp3pd PASSED                                                                                                                                                                      [ 66%]
tests/test_fair.py::test_rcp45 PASSED                                                                                                                                                                       [ 77%]
tests/test_fair.py::test_rcp6 PASSED                                                                                                                                                                        [ 88%]
tests/test_fair.py::test_rcp85 PASSED                                                                                                                                                                       [100%]
============= 9 passed
```

### CODE REVIEW

**Comment by znicholls** [comment]
Awesome cheers Robert! @chrisroadmap I think we should be able to maintain Python 3 compatibility in future? The common subset should allow us to do everything we need?

**Comment by rgieseke** [comment]
I think the only thing to check would be to make sure that no variable that you divide by is an integer which would have different results in Python 2 and 3. If both are floats there is no problem. I'd think the tests would have caught this if it were the case.

In general it will become more difficult to maintain Python *2* compatibility soon:
https://pythonclock.org/

On Jan. 1, 2019 any new features in Numpy will only support Python 3, bug fixes will be applied until Dec 31, 2019
https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst

http://www.python3statement.org/

**Comment by chrisroadmap** [comment]
This is excellent, thanks @rgieseke! Yes this should be easy to maintain in future. In general I try and be explicit when defining floats but that doesn't mean that something hasn't slipped through the net somewhere. We should verify that the input array conversion produces float arrays where applicable if the user passes integer arguments.

**Comment by rgieseke** [comment]
> We should verify that the input array conversion produces float arrays where applicable if the user passes integer arguments.

That's an important point! The easiest is probably to add

```python
from __future__ import division
```

to the codebase. This should be easier than riddling the code with type checks or conversions.

Thanks for the quick merge, looking forward to playing more with FAIR!

**Pull request merged**
