### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Adds basic github actions. Things are still a bit of a mess but let's not do everything at once.

Please confirm that this pull request has done the following:

- [x] Tests added (N/A)
- [x] Documentation added (where applicable) (N/A)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable) (N/A)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <http://link-to-pr.com>`_) Added feature which does something
- (`#XX <http://link-to-pr.com>`_) Fixed bug identified in (`#XX <http://link-to-issue.com>`_)
```

### CODE REVIEW

**Comment by znicholls** [comment]
@JGBroadbent we made a bit of a mess of this so this PR does more than I would like. Basically, all it does it get things setup so we can sensibly run the tests using GitHub actions (i.e. continuous integration). Things aren't set up that well yet so the tests are actually only running on my fork for now (see https://github.com/znicholls/FAIR/actions), but should be fixed soon. 

@rgieseke if you're interested, your eyes are always welcome!

**Review by JGBroadbent — APPROVED** [review]
Looks good to me, what changes do we need to run it away from your Fork @znicholls ?

**Comment by znicholls** [comment]
> Looks good to me, what changes do we need to run it away from your Fork @znicholls ?

I'm not completely sure. My hope is that once we merge, it'll be in the main repo so things will start running. If that doesn't happen, I'll dig deeper.

**Comment by JGBroadbent** [comment]
Ok, sounds good.

**Comment by znicholls** [comment]
Going to assume silence from @njleach and @chrisroadmap means go for it so will merge this now so we can keep moving

**Pull request merged**
