### PR TITLE
adds common classes for Emissions, Concentrations, Forcings

### PR DESCRIPTION
**Pull request by nsfmc**
the classes simplify the rcp_.py files while providing a consistent interface to the data when ingesting arbitrary rcp csv files (i.e. useful in cases where you don't want or need to import all three Emissions/Concentrations/Forcings)

also useful in cases where you need to override specific property behavior (i.e. scaling or reformatting some specific property dynamically)
```python
from fair.RCPs import types

 class SpecialForcing(types.Forcing):                              
     def __init__(self, *args, **kwargs):
         super(SpecialForcing, self).__init__(*args, **kwargs)

     @property
     def year(self):
         return map(int, super(SpecialForcing, self).year.tolist())
```
this subclassed `Forcing` would no longer emit an ndarray for years, but instead a simple python list of `int`s. This is an pretty contrived example, but i think fairly illustrative.

The goal here was to maintain api parity while adding some minor functionality. Tests pass at the same rate as before. 

specific additions:
- `._filename` is exposed
- each instance's `__repr__` exposes an Emission/Concentration/Forcing's source filename as well.

# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added (tests pass at same rate as before)
- [ ] Documentation added (where applicable)
- [ ] Example added (either to an existing notebook or as a new notebook, where applicable)
- [ ] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <http://link-to-pr.com>`_) Added feature which does something
- (`#XX <http://link-to-pr.com>`_) Fixed bug identified in (`#XX <http://link-to-issue.com>`_)
```

### CODE REVIEW

**Comment by nsfmc** [comment]
if this isn't useful to the project or if it introduces a level of complexity you'd rather not deal with, please feel free to close this pr, mostly submitted to see if it was useful to anybody else.

**Comment by znicholls** [comment]
definitely moves in the right direction for v2.0 @chrisroadmap

**Comment by chrisroadmap** [comment]
closing as part of general clean and moved beyond this treatment in v2 - thanks all the same :+1:

**Comment by nsfmc** [comment]
hahaha @chrisroadmap i have zero memory of doing this (it was clearly another time), thanks for closing it out all the same 🤘🏽

**Pull request closed without merging**
