### PR TITLE
Speed up scmdf conversion

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added (N/A)
- [x] Documentation added (where applicable) (N/A)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable) (N/A)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <http://link-to-pr.com>`_) Added feature which does something
- (`#XX <http://link-to-pr.com>`_) Fixed bug identified in (`#XX <http://link-to-issue.com>`_)
```

### CODE REVIEW

**Comment by znicholls** [comment]
@chrisroadmap not perfect but a start

**Comment by znicholls** [comment]
you could make it faster again if you were more opinionated about the units coming in (and forced users to interpolate before they started)

**Comment by chrisroadmap** [comment]
Tests pass with scmdata 0.5.2 but fail for me with scmdata 0.4.3 and 0.5.0:

What's the minimum requirement? 0.5.2?

```
tests/integration/test_scmdf.py:51:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
fair/tools/scmdf.py:205: in scmdf_to_emissions
    hist_df = ssp245_world_emms_holder.values_fair_units.filter(
fair/tools/scmdf.py:45: in values_fair_units
    ssp_df_hist = self.values
fair/tools/scmdf.py:32: in values
    lowercase_cols=True
/nfs/b0110/Users/mencsm/miniconda3/envs/fair-dev/lib/python3.7/site-packages/scmdata/run.py:375: in __init__
    self._init_timeseries(data, index, columns, **kwargs)
/nfs/b0110/Users/mencsm/miniconda3/envs/fair-dev/lib/python3.7/site-packages/scmdata/run.py:405: in _init_timeseries
    (_df, _meta) = _read_file(data, **kwargs)
/nfs/b0110/Users/mencsm/miniconda3/envs/fair-dev/lib/python3.7/site-packages/scmdata/run.py:67: in _read_file
    return _format_data(_read_pandas(fnames, *args, **kwargs))
```
...
```
>           df = pd.read_csv(fname, *args, **kwargs)
E           TypeError: parser_f() got an unexpected keyword argument 'lowercase_cols'

/nfs/b0110/Users/mencsm/miniconda3/envs/fair-dev/lib/python3.7/site-packages/scmdata/run.py:98: TypeError
```

**Comment by znicholls** [comment]
Yep 0.5.2 I guess

**Pull request merged**
